chore:  send all GPU IDs in a healthy event raised from the GPU health monitor
This MR add following capabilities:

1. During initialization, send GPU IDs with for clearing XID errors (NGCC-23293)

From platform connector pod:

```
I0321 10:17:55.210347       1 platform_connector_server.go:50] Health events version:1 events:{version:1 agent:"gpu-health-monitor" componentClass:"GPU" checkName:"GpuXidError" isHealthy:true message:"NoXidErrorDetected" entitiesImpacted:{entityType:"GPU" entityValue:"0"} entitiesImpacted:{entityType:"GPU" entityValue:"1"} entitiesImpacted:{entityType:"GPU" entityValue:"2"} entitiesImpacted:{entityType:"GPU" entityValue:"3"} entitiesImpacted:{entityType:"GPU" entityValue:"4"} entitiesImpacted:{entityType:"GPU" entityValue:"5"} entitiesImpacted:{entityType:"GPU" entityValue:"6"} entitiesImpacted:{entityType:"GPU" entityValue:"7"} generatedTimestamp:{seconds:1742552275 nanos:203478000} nodeName:"gke-tg220000-dgxc-runai--customer-gpu-22dbdec4-fgpr"} received
```

1. In the node-labeler event informer(add in [this ](https://gitlab-master.nvidia.com/dgxcloud/mk8s/k8s-addons/nvsentinel/-/merge_requests/159)MR), there were some issues from API side which was leading to `CrashLoopBackOff`:

   ```
     File "//node_watcher.py", line 84, in main
       for event in w.stream(
     File "/usr/local/lib/python3.10/dist-packages/kubernetes/watch/watch.py", line 165, in stream
       for line in iter_resp_lines(resp):
     File "/usr/local/lib/python3.10/dist-packages/kubernetes/watch/watch.py", line 56, in iter_resp_lines
       for seg in resp.stream(amt=None, decode_content=False):
     File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 624, in stream
       for line in self.read_chunked(amt, decode_content=decode_content):
     File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 816, in read_chunked
       with self._error_catcher():
     File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
       self.gen.throw(typ, value, traceback)
     File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 461, in _error_catcher
       raise ProtocolError("Connection broken: %r" % e, e)
   urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
   ```

   We catch that exception as that is not an indication of an underlying issue.

Closes NGCC-23293

Closes NGCC-23293

See merge request dgxcloud/mk8s/k8s-addons/nvsentinel!162